Add a core status attribute
EmulatorJS/build pull request #15
Opened 2024-08-01 05:18 UTC by michael-j-green

Adds an attribute called "status". The intention is to allow EJS to display the state of the build to manage user expectations if a core is still in test or not completely functional.

Status can have one of the following values:

* ``0`` or not set = ``stable``
* ``1`` = ``beta``
* ``2`` = ``experimental``
* ``3`` = ``don't build`` - the build script will skip building the core

2024-08-01 05:22 UTC, michael-j-green commented
@ethanaobrien: I've only set the ones I know to be ``experimental``, if there are others you'd like me to mark with a different status, let me know before accepting this PR.

2024-08-01 14:13 UTC, ethanaobrien commented
Here are my thoughts real quick. 

I don't think cores should be added to the cores.json at all if they don't build - if that happens, there are always going to be people asking why it isn't building, and not even trying.

I also kinda think that with how this project runs, that beta and experimental are both one core (like your changes to cores.json only used experimental, with none marked as beta)

Let me know on your thoughts on these

2024-08-01 14:52 UTC, michael-j-green commented
You're right of course that they wouldn't be in cores.json unless they had passed some basic build testing. But I wanted to be able to include sub-optimal cores in the script to allow for testing purposes.

The ones I marked experimental is because they do build, but I still need to do some proper testing to ensure they work. They would move up to beta (though that could be relabled to "unstable" perhaps?) with more testing.

I was thinking along the lines of cores like picodrive which we know is a bit dodgy, could have a label of beta because there were issues with running it, and giving it a label like that sets end user expectations.

Having the value there also allows us to filter work in progress or known-faulty cores from release builds, but leave them in nightlies for testing purposes.

This PR is very much in the area of a proposal/suggestion :)

2024-08-12 04:36 UTC, ethanaobrien requested changes

2024-08-12 04:36 UTC, ethanaobrien commented on build.sh
> +    if [ -a "$status" != 3 ]; then
Could we "if status == 3 then continue"? or is that not available in bash?

2025-02-26 02:39 UTC, closed without merging